### PR TITLE
Uzbekistan data portals

### PR DESCRIPTION
**Pull request by augusto-herrmann**
Added the two data portals from Uzbekistan and created a pull request do that we can discuss and review this (issues #202 and #206).

### CODE REVIEW

**Comment by augusto-herrmann** [comment]
@todrobbins, what do you think the `license-id` field should be for the open data portal? It's a custom license, which AFAIK has yet to be reviewed as considered open by the [Open Definition](https://opendefinition.org/). For now I'm using `other-at`.

Also, what do we usually do with the `location` field, in the case of a country? Look up the coordinates for the centroid? For now I'm leaving it blank. I suppose that until it is filled out it won't be shown on the map.

**Comment by todrobbins** [comment]
Thanks for this @augusto-herrmann!

I'd say leave it as `other-at` for the time being. We will probably need to review at some point. We will need a location or it won't show on the map. Let's use this centroid for the capital Toshkent/Tashkent: `41.316667,69.266667`

**Comment by hurriyat1985** [comment]
Dear Mr.Tod Robbins, Mr. Augusto Herrman and other dataportals.org team,
We would like to thank you and your team for supporting the efforts of countries, to improve their open data systems and harness the advancements of the data revolution. 
And we want to say that we don’t mind to use the centroid for the capital Toshkent/Tashkent: 41.316667,69.266667 as a location, as our main office is situated in Tashkent.
  We wish  success in your prospactive work. 
>Среда, 8 июля 2020, 0:54 +03:00 от Tod Robbins <notifications@github.com>:
> 
> 
>Thanks for this  @augusto-herrmann !
>I'd say leave it as other-at for the time being. We will probably need to review at some point. We will need a location or it won't show on the map. Let's use this centroid for the capital Toshkent/Tashkent: 41.316667,69.266667
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
HXB Berdievna

**Comment by augusto-herrmann** [comment]
> @augusto-herrmann a minor nit, but could you change `Cc-by-sa` to `cc-by-sa`? All good otherwise!

Sure! That was a LibreOffice auto capitalization thing that somehow I missed. All fixed now!

Note to self: still need to add Goodtables.io to Github actions to automatically check pull requests. I'm doing goodtables checks only locally – and manually now. The data package is valid.

**Pull request merged**
