### PR TITLE
Update portals.csv adding Sweden's national data portal

### PR DESCRIPTION
**Pull request by mattiasaxell**
Also updating situation on Swedish portals replaced by national portal.

### CODE REVIEW

**Comment by mattiasaxell** [comment]
@augusto-herrmann Would you be able to have a look at this PR and merge? :smile:

**Review by augusto-herrmann — APPROVED** [review]
It looks great! Thanks for the PR, @mattiasaxell !

**Comment by mattiasaxell** [comment]
@augusto-herrmann Thanks for merge. Do I understand correctly it does not deploy to dataportals.org? I also do not see the map from Leaflet.

**Comment by augusto-herrmann** [comment]
Yes, I have just checked here and there is [no Github Action](/okfn/dataportals.org/tree/master/.github/workflows) for site deployment. I think it was being done manually before. That's yet one more thing that needs fixing.

**Pull request merged**
