### PR TITLE
fix #236: migrate to frictionless repository

### LINKED ISSUE #236: Migration from Goodtables to Frictionless Repository
Hi,

Goodtables.io is going to be deprecated in 2022, we, therefore, recommend migrating to the new Frictionless Repository (https://repository.frictionlessdata.io/) continuous data validation system provided by Frictionless Data. The core difference between the two projects is that Frictionless Repository doesn't rely on any hosted infrastructure except for Github Actions which makes this project more sustainable. Also, it uses a newer Frictionless Framework under the hood that brought many improvements over the old goodtables-py library in terms of validation quality and performance.

If you have any doubts or questions, please come and ask in [our Discord chat](https://discord.com/invite/Sewv6av) or in the [GitHub Discussion](https://github.com/frictionlessdata/project/discussions).

### PR DESCRIPTION
**Pull request by augusto-herrmann**
Is this the correct way to migrate from Goodtables.io to Frictionless Repository, @sapetti9 @roll ?

### CODE REVIEW

**Comment by roll** [comment]
Hi @augusto-herrmann, looks good to me :+1:

**Comment by augusto-herrmann** [comment]
Thanks, @roll ! Happy holidays and an excellent new year! :christmas_tree:

**Comment by augusto-herrmann** [comment]
@roll it seems the validation is happening, but I can't see the validation report. For example: https://repository.frictionlessdata.io/report/?user=okfn&repo=dataportals.org&flow=portals&run=1622883256

The badge [here](https://github.com/okfn/dataportals.org/tree/master/data) also does not seem to work for some reason.

Could you please help debug this?

**Comment by roll** [comment]
Thanks @augusto-herrmann,

We will investigate after the break - https://github.com/frictionlessdata/repository/issues/20

**Comment by augusto-herrmann** [comment]
Of course. Thanks, @roll ! Enjoy the break. :relaxed:

**Pull request merged**
