### PR TITLE
fix link to caboverde.opendataforafrica.org (discussing line endings)

### PR DESCRIPTION
**Pull request by harry-wood**
I had thought the coordinates were a mistake, but no. There's some little islands there! But we can remove inappropriate precision on the coordinates. And more importantly... 

the link is caboverde.opendataforafrica.org (portuguese spelling)

### CODE REVIEW

**Comment by harry-wood** [comment]
ok. I just edited one line of the file using the online github file editor. I see what you mean.  The github editor must have swapped the line endings.  I can't even see what my change was.

(It was this line) 

```
capeverde_opendataforafrica,Open Data for Cape Verde,http://caboverde.opendataforafrica.org,African Development Bank Group,African Development Bank Group,,,Open data portal for Capr Verde,africa,other-at,,Cape Verde,"16.00,-24.00",CV,en,active,2013-08-29T07:47:18.149Z,,,,
```

That seems like a problem which shouldn't have occurred. [github help on dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/) suggests maybe you'd have to put a `.gitattributes` file to make it behave better. Bit of a pain.

**Comment by rgrp** [comment]
@harry-wood could you try making the edit again? I've just removed the ^M line endings and pushed and it would be good to see if the edit via the editor now only edited that one line.

Thank-you once again for the contribution :-)

**Comment by harry-wood** [comment]
OK. I had to do it as a new pull request. That's looking better: https://github.com/okfn/dataportals.org/pull/66/files  

but if you want to keep "DOS" line endings as per the standard CSV spec, maybe the github editor respects that only if you tell to `.gitattributes file` . Not sure.

**Comment by harry-wood** [comment]
We can discuss line endings here, if anyone has ideas, but I'll close this PR to avoid confusion. https://github.com/okfn/dataportals.org/pull/66 duplicates the same change, but more successfully

**Pull request closed without merging**
