### PR TITLE
adds an issue_template for portal submissions

### PR DESCRIPTION
**Pull request by todrobbins**
first step in the transition from Google Forms submissions to Github

### CODE REVIEW

**Comment by todrobbins** [comment]
@rufuspollock I guess I failed to notice I don't have write access on this repository. 😁

**Comment by todrobbins** [comment]
@danfowler can I get write access to this repo? I'm the new maintainer per @rufuspollock's request.

**Comment by rufuspollock** [comment]
@todrobbins you should have write access now 😄

**Comment by todrobbins** [comment]
We're live!

screen shot 2017-04-07 at 9 36 46 am

**Pull request merged**
