### PR TITLE
#48 (data updates) and #55 (markdown in leaflet popup)

### LINKED ISSUE #55: Information box not processing markdown
Not sure if this is an error in the spreadsheet data or the information box.

Spreadsheet description column has cells with markdown. The information box does not process the markdown.
screenshot 2015-08-21 20 58 14

Could be added to #37

### PR DESCRIPTION
**Pull request by marks**
which is `description` attribute converted to HTML courtesy of `marked` module

### CODE REVIEW

**Comment by rgrp** [comment]
@marks great stuff!

@Stephen-Gates I'll leave you to review formally and merge :-)

**Comment by Stephen-Gates** [comment]
@rgrp sorry for the delay. I'm happy to review data changes but not qualified to review code changes. If someone can explain how I could test the changed code before merging the request, I could do that. I'm not confident to merge a code change by just reading the code. @marks change appears minor but would like to merge future requests with confidence or leave it to others.

**Comment by rgrp** [comment]
@Stephen-Gates ok i'll review these and deploy. In general, for minor we're happy to do a code review and revert if it breaks live ;-)

**Comment by rgrp** [comment]
@marks this is really appreciated. As a minor request for future it is great to have distinct pull requests for different bunches of changes - e.g. a code feature in one PR and data improvements separately. No problem this time of course!

**Comment by marks** [comment]
@rgrp will do for next time!

**Pull request merged**
