### PR TITLE
Added city-level data portals from the Google spreadsheet

### PR DESCRIPTION
**Pull request by jgkim**
Added city-level data portals from the Google spreadsheet (cf. https://discuss.okfn.org/t/city-level-data-portals/1131).

### CODE REVIEW

**Comment by rgrp** [comment]
@Stephen-Gates would you like the honour of reviewing our first proper pull request as our Portal expert :-)

**Comment by rgrp** [comment]
@jgkim sorry - i just realize there was another alphabetizing pull request. could you resubmit after merging current master.

**Comment by jgkim** [comment]
I merged it. ;)

**Comment by Stephen-Gates** [comment]
Thanks for your contribution @jgkim and the honour @rgrp

**Pull request merged**
