### PR TITLE
JSON Download and Licence in Footer

### PR DESCRIPTION
**Pull request by Stephen-Gates**
Addresses #45 Licence. Please confirm single link to PDDL is sufficient
as submission form states data is licensed as both CCZero and/or PDDL

Addresses #33 and #17 JSON API in Site Footer

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
Download CSV may not be as simple as publish Google doc and add link in footer. Discovering weird treatment of special characters when viewing download using Excel.

**Comment by mattfullerton** [comment]
OK, then the medium term goal should be to do it from node.js.

Do you still want the pull request merged?

@rgrp - thoughts on the license issue? Changing the form to match is simple enough.

**Comment by rgrp** [comment]
@mattfullerton yes doing this as just PDDL is fine.

Re CSV direct google download link is fine for now. Next step (cc @Stephen-Gates) would be to Tabular Data Package-ize the CSV file by adding a datapackage.json in this repo for it ;-) see http://data.okfn.org/doc/publish-tabular

**Comment by rgrp** [comment]
@mattfullerton i'll leave you to merge and do the deploy :-)

**Comment by Stephen-Gates** [comment]
@rgrp so the next step for data packaging is to create something like https://github.com/okfn/opendatasites but in this repository? There is already a Data directory that contained (an old) CSV file that people recently issued pull requests on to change data. @mattfullerton just moved the file to Archive to avoid future pull requests.

So is everyone happy to put CSV back and add update it as part of the data release process?

I'll focus on reviewing submissions and writing documentation while you decide.

**Comment by rgrp** [comment]
@Stephen-Gates we actually won't put the CSV back in the github repo - we'll just point to the CSV link that google docs gives us.

**Comment by Stephen-Gates** [comment]
@mattfullerton can this be progressed to support [this request](https://discuss.okfn.org/t/data-portals-in-csv-kml-formats/1509)?

**Pull request merged**
