### PR TITLE
OKI logo, 'Foundation' to 'International'

### PR DESCRIPTION
**Pull request by ljoelle**

### CODE REVIEW

**Comment by rgrp** [comment]
@ljoelle we generally prefer the logo to lives in assets.okfn.org rather than local as updating is easier we get better caching etc. This seems a great change but could we get the relevant OKI logo into assets.okfn.org and then update to point to that?

**Comment by pwalsh** [comment]
@rgrp we decided not to use assets@ going forward as it is a manual process that several people find annoying, and involves sysadmin tickets just to get the assets live.

**Comment by pwalsh** [comment]
But @rgrp your comment did prompt me to act on this in a more decisive manner :). I'm deprecating assets.okfn.org (leaving it read only forever, of course), and have set up a fully automated flow for new assets going forward:

* https://github.com/okfn/a
* https://travis-ci.org/okfn/a
* http://a.okfn.org/img/oki-logo-rgb.png

@ljoelle my fault entirely as I was not able to give this the attention it deserves. I've updated @nigelbabu with the new setup I just hacked on, and the work will be seamless going forward (pushing to the assets server is completely automated).

**Comment by rgrp** [comment]
@ljoelle great - so you can now point to a.okfn.org stuff instead. do you want to change this pull request or do a new one :-)

**Comment by rgrp** [comment]
Ah i see now -- you have a separate PR.

BTW as a tip i would be submitting the additional images as part of the PR rather than adding them directly. We need to remove the image you added - could you do a PR for that.

**Comment by rgrp** [comment]
@ljoelle that is the image here https://github.com/okfn/dataportals.org/blob/master/public/img/oki-landscape-rgb.png

**Comment by ljoelle** [comment]
@rgrp I sent a PR to remove the additional image and changed the logo to point to a.okfn.org. Thanks!

**Pull request merged**
