### PR TITLE
Fixed broken link in catalogs

### PR DESCRIPTION
**Pull request by jrovegno**
www.data.gov.cl was replaced with datos.gob.cl

### CODE REVIEW

**Comment by mattfullerton** [comment]
Sorry, this file is simply an export and does not affect the data on the site. Right now the best ways to submit *changes* is to submit a new entry or a github issue.

**Comment by Stephen-Gates** [comment]
You can also request a change at https://discuss.okfn.org/c/open-knowledge-labs/dataportals if that's easier

**Comment by mattfullerton** [comment]
Yes, actually that might be best. We can keep github for site code changes.

**Comment by Stephen-Gates** [comment]
Request was added to OK Forum and database updated  :-)

**Pull request closed without merging**
